### ISSUE TITLE
Convert VTK file to OBJ with Meshio 

### ISSUE THREAD

**Issue by Biaggio74** [CALFEM/calfem-python#22]
Hi, congrats on this nice library, I think it stands out among other open source libs for FEA with its simplicity and "engineer" friendly API.

I try to work further with a meshed elevation profile for CFD analysis with my collaborators and I would need to convert the VTK output file of the mesh into `OBJ` or `STL` files. I thought `Meshio` is the solution but unfortunately it is not capable of reading the produced VTK file by CALFEM as it is POLY DATA.

See the error message extract as below:
`meshio._exceptions.ReadError: Only VTK 'UNSTRUCTURED_GRID', 'STRUCTURED_POINTS', 'STRUCTURED_GRID', 'RECTILINEAR_GRID' supported (not POLYDATA).`

Could you suggest a work around how to export this VTK into OBJ or STL file? 

See an example attached about a terrain.
<img width="1328" alt="Screenshot 2021-05-28 at 11 14 20" src="https://user-images.githubusercontent.com/11397475/120068149-859d7300-c07f-11eb-9e07-9808e419be7d.png">

**Comment by jonaslindemann** [comment]
Try to open it in ParaView and export from there.
