### ISSUE TITLE
Redesigning tutorial/code examples

### ISSUE THREAD

**Issue by bagustris** [CALFEM/calfem-python#23]
Dear Calfem for Python developers, 

Thank you for your great effort in providing a simple yet intuitive program for the finite element method. This is very helpful for me to re-learn and tutoring FEM. To gain more adoption, I am proposing the new redesign of tutorial or code examples in the Calfem-for Python documentation. What I am proposing is:
1. Use existing python example files in `examples` directory inside of writing rst file from scratch.This can be achieved by using `literalinclude` in rst file.
2. Using jupyter-notebook if possible. This can be achieved using nbsphinx extension.

Both methods ensure that the tutorial or code examples are from the most recent example version. Also, we don't need to update rst file once we modified the original examples.

I believe documentation especially tutorial is a crucial part of software development to gain market share. I have been able to convert the current tutorial to above approaches and will make PR if this proposal is accepted.

Let me know your opinion.

**Comment by jonaslindemann** [comment]
I think it would be a great idea. Send a PR and I will look at it.

Jonas
