### ISSUE TITLE
Feature request: `calfem.__version__`

### ISSUE THREAD

**Issue by bagustris** [CALFEM/calfem-python#31]
It is common practice in Python to have a version in parent coding structure. For example:  
```
import numpy
numpy.__version__ # print version, e.g, '1.21.5'
import scipy
scipy.__version__
```
I would like to request that feature in Calfem so that I can do:  
```
import calfem
calfem.__version__
```

That feature is beneficial when teaching or collaborating, that is to make we are at the same version.
I think it is easy to implement (adding lines in `setup.py`, @jonaslindemann ?).

**Comment by jonaslindemann** [comment]
Sounds very reasonable. I will check for the next release. I am currently working on integrating a lot of new functionality such as an interactive geometry editor and visualisation functions implemented using the vedo library.

**Comment by bagustris** [comment]
I downloaded the latest release, now it has this feature, but it shows the previous version.

```shell
bagus@L140MU:~$ python3 -m pip list | grep calfem
calfem-python           3.5.12               /tmp/calfem-python
bagus@L140MU:~$ python3
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import calfem
>>> calfem.__version__
'3.5.10'
```

The version should be 3.5.11 per release, but pip shows 3.5.12 while `calfem.__version__` shows 3.5.10.
Not a critical issue, but make a confusion.
