### ISSUE TITLE
Problem with combinaison  of blocks

### ISSUE THREAD

**Issue by MorphoBacca** [CALFEM/calfem-python#37]
Hello,
I am trying to combine 6 blocks with common faces between blocks. I have a problem when I try to mesh with an error like "Incompatible surface 28 in transfinite volume 5". The problem seems linked to points ID but I can't find a solution. My exemple is attached:

[beam_block.zip](https://github.com/CALFEM/calfem-python/files/8621828/beam_block.zip)

Could you help me with this problem, please?
Thank you in  advance

**Comment by jonaslindemann** [comment]
I will look into it.

**Comment by njotway** [comment]
Hi. 
Can you please explain how you resolved the issue with incompatible surface?
I have a similar problem that says:   'Exception: Incompatible surface 1 in transfinite volume 1'
My structured surface grids looks good on all faces/edges so they should join to enclose a 3d region of space.
When I try to use the 6 surfaces to build a structured volume mesh I get the same type of transfinite incompatibility error.
I've been stuck on this for days and cannot find a solution. 
Please let me know if you have any advice (py script is attached). 
Thank you very much.

[hps3d_v02.zip](https://github.com/CALFEM/calfem-python/files/13384890/hps3d_v02.zip)

**Comment by jonaslindemann** [comment]
Working on it. I have not worked a lot with structured surfaces to be honest. Also, there can be a bug in our code or a topology related issue. We use GMSH as the underlying mesh generator, so you might find some hints there.

**Comment by njotway** [comment]
Thank you for the response. 
Yes, I've had a good look through the gmsh reference manual but was unable to find any useful information. 
Note that it all works perfectly when using g.addVolume() so I'll probably just settle for the unstructured volume approach. At least I can still keep the structured surface grid and maintain decent global mesh quality statistics. 
Your work here is greatly appreciated. Keep it up!
All the best.
