### ISSUE TITLE
Not sure about type of error

### ISSUE THREAD

**Issue by Larsdi** [CALFEM/calfem-python#4]
Traceback (most recent call last):
  File "exmp1.py", line 10, in <module>
    import calfem.vis as cfv
  File "/usr/local/lib/python3.7/site-packages/calfem/vis.py", line 24, in <module>
    visApp = vv.use('qt5') # use qt4
  File "/usr/local/lib/python3.7/site-packages/visvis/functions/use.py", line 47, in use
    return vv.backends.use(backendName)
  File "/usr/local/lib/python3.7/site-packages/visvis/backends/__init__.py", line 218, in use
    raise RuntimeError('Given backend "%s" could not be loaded.' % tmp)
RuntimeError: Given backend "/usr/local/lib/python3.7/site-packages/visvis/backends/pyqt5.xxx" could not be loaded.
larsdigerud@Larss-MBP examples_TMM4135 %

**Comment by RomainGuimbal** [comment]
Hi I have the same issue, have you found what it is?

**Comment by jonaslindemann** [comment]
How did you install calfem-python? It seems that the visvis package is missing. 

Jonas

**Comment by jonaslindemann** [comment]
Do you have administrative access to your computer? Are you doing a pip user installation?

**Comment by mjjohnson99** [comment]
I do have admin privileges but that was not doing a user installation. I found in the example files some difference in approach in importing - which now lets me run after install pyqt5-tools and calling "from calfem.qt5 import *" first.

Upon running https://github.com/CALFEM/calfem-python/blob/master/examples/ex_tutorial_1.py with quadrangle there are gaps in the mesh though?
![image](https://user-images.githubusercontent.com/103999280/206666982-af18b6df-1d04-4fea-b694-14b67339f05e.png)

**Comment by jonaslindemann** [comment]
Try changing the mesh.el_size_factor somewhat. I have seen this with gmsh before with quad-meshes.

**Comment by Sashank77** [comment]
TypeError                                 Traceback (most recent call last)
Cell In[110], line 1
----> 1 cfc.assem(Edof[0, :],k,ke2)
      2 cfc.assem(Edof[1, :],k,ke1)
      3 cfc.assem(Edof[2, :],k,ke2)

File E:\anaconda\Lib\site-packages\calfem\core.py:5266, in assem(edof, K, Ke, f, fe)
   5264 if edof.ndim == 1:
   5265     idx = edof-1
-> 5266     K[np.ix_(idx, idx)] = K[np.ix_(idx, idx)] + Ke
   5267     if (not f is None) and (not fe is None):
   5268         f[np.ix_(idx)] = f[np.ix_(idx)] + fe

TypeError: 'float' object is not subscriptable

**Comment by jonaslindemann** [comment]
Please, check that the indexes in Edof are integers. For example:

Edof = np.array([
    [1.0, 2.0, 3.0],
    [4.0, 5.0, 6.0]
])

Can’t be used with assem(). This is valid for assem.

Edof = np.array([
    [1, 2, 3],
    [4, 5, 6]
])


Från: Sashank77 ***@***.***>
Skickat: den 25 december 2024 09:58
Till: CALFEM/calfem-python ***@***.***>
Kopia: Jonas Lindemann ***@***.***>; Comment ***@***.***>
Ämne: Re: [CALFEM/calfem-python] Not sure about type of error (#4)


TypeError Traceback (most recent call last)
Cell In[110], line 1
----> 1 cfc.assem(Edof[0, :],k,ke2)
2 cfc.assem(Edof[1, :],k,ke1)
3 cfc.assem(Edof[2, :],k,ke2)

File E:\anaconda\Lib\site-packages\calfem\core.py:5266, in assem(edof, K, Ke, f, fe)
5264 if edof.ndim == 1:
5265 idx = edof-1
-> 5266 K[np.ix_(idx, idx)] = K[np.ix_(idx, idx)] + Ke
5267 if (not f is None) and (not fe is None):
5268 f[np.ix_(idx)] = f[np.ix_(idx)] + fe

TypeError: 'float' object is not subscriptable
