### ISSUE TITLE
Error in beam2ts()

### ISSUE THREAD

**Issue by ojseryd** [CALFEM/calfem-python#46]
Found an error on line 737 in core.py:

`
v = np.concatenate((np.power(x, 3), np.power(x, 2), x, one), 1) * \
        C4+qy/(24*EI)*np.np.power(x, 4)-qy/(2*GAK)*np.power(x, 2)
`

should be

`
v = np.concatenate((np.power(x, 3), np.power(x, 2), x, one), 1) * \
        C4+qy/(24*EI)*np.power(x, 4)-qy/(2*GAK)*np.power(x, 2)
`

**Comment by jonaslindemann** [comment]
I will check.
