### ISSUE TITLE
[Question] Can you use this library for Python 3.10?

### ISSUE THREAD

**Issue by Martin15135215** [CALFEM/calfem-python#50]
seput.py does not contain Python 3.10

https://github.com/CALFEM/calfem-python/blob/b9ea36db193a8f2ab57add95b2af7b2a3c7882dc/setup.py#L65-L72

**Comment by Martin15135215** [comment]
Python 3.7 is end-of-life → see [here](https://peps.python.org/pep-0537/#lifespan)

**Comment by jonaslindemann** [comment]
Fixed.
