### ISSUE TITLE
Question regarding Licence & commercial usage 

### ISSUE THREAD

**Issue by Martin15135215** [CALFEM/calfem-python#56]
The licence is MIT, see here https://github.com/CALFEM/calfem-python/blob/master/LICENSE

![image](https://github.com/CALFEM/calfem-python/assets/110968398/0c4dea77-c2c2-4257-8879-25574bba9d25)

With MIT, commercial usage is permitted. So why is this line in the README:

https://github.com/CALFEM/calfem-python/blob/fd3a4d65f34f386b9009c1824b1f27aed0ffb4a3/README.md?plain=1#L20

Can you tell me if it is possible to use this code for commercial use?

**Comment by jonaslindemann** [comment]
It is possible to use commercially. I agree that this section is weirdly formulated. I have updated it in the master-branch.

**Comment by Martin15135215** [comment]
Thanks for the clarification!
