### ISSUE TITLE
Inconsistent comments in the documentation

### ISSUE THREAD

**Issue by VilmerD** [CALFEM/calfem-python#61]
Students discovered an inconsistency in the documentation, under the mesh generation chapter, where the mesh properties are described it says:

```
mesh.elType = 3          # Degrees of freedom per node.
mesh.dofsPerNode = 1     # Factor that changes element sizes.
mesh.elSizeFactor = 0.15 # Element size Factor
```

But it should say something like

```
mesh.elType = 3         # Element type is quadrangle.
mesh.dofsPerNode = 1      # Degrees of freedom per node.
mesh.elSizeFactor = 0.15 # Factor that changes element sizes.
```
I know it's only a comment but it's important since the software is used for teaching, and so the users must get correct information.

**Comment by jonaslindemann** [comment]
Fixed in upcoming 3.6.6
