### ISSUE TITLE
Documentation Inconsistency

### ISSUE THREAD

**Issue by VilmerD** [CALFEM/calfem-python#62]
Another inconsistency in the documentation.

The doc-string is not up to date with the code. In particular the variable names do not match.

https://github.com/CALFEM/calfem-python/blob/8c9746482e6545c461aad440ee4d9fba7201f447/calfem/vis_mpl.py#L505C9-L505C12

**Comment by jonaslindemann** [comment]
Thanks again. Will check.

Från: Vilmer Dahlberg ***@***.***>
Skickat: den 29 januari 2024 14:21
Till: CALFEM/calfem-python ***@***.***>
Kopia: Subscribed ***@***.***>
Ämne: [CALFEM/calfem-python] Documentation Inconsistency (Issue #62)


Another inconsistency in the documentation.

The doc-string is not up to date with the code. In particular the variable names do not match.

https://github.com/CALFEM/calfem-python/blob/8c9746482e6545c461aad440ee4d9fba7201f447/calfem/vis_mpl.py#L505C9-L505C12
