### ISSUE TITLE
gsmh

### ISSUE THREAD

**Issue by shayanmazloom** [CALFEM/calfem-python#7]
Traceback (most recent call last):
  File "C:/Users/HP/AppData/Local/Programs/Python/Python37/hkl.py", line 91, in <module>
    coords, edof, dofs, bdofs, elementmarkers = mesh.create()
  File "C:\Users\HP\AppData\Local\Programs\Python\Python37\lib\site-packages\calfem\mesh.py", line 230, in create
    raise IOError("Error: Could not find GMSH. Please make sure that the \GMSH executable is available on the search path (PATH).")
OSError: Error: Could not find GMSH. Please make sure that the \GMSH executable is available on the search path (PATH).

**Comment by jonaslindemann** [comment]
Make sure to install GMSH (http://gmsh.info/) and add it to the search PATH in Windows. In anaconda GMSH can be installed by using 

conda install python-gmsh

**Comment by Nikan888** [comment]
gmsh is in the PATH, but issue is still occured

Traceback (most recent call last):
  File "form_plate_mesh.py", line 26, in <module>
    coords, edof, dofs, bdofs, elementmarkers = mesh.create()
  File "D:\Programs\Python3-64bit\lib\site-packages\calfem\mesh.py", line 256, in create
    "Error: Could not find GMSH. Please make sure that the \GMSH executable is available on the search path (PATH).")
OSError: Error: Could not find GMSH. Please make sure that the \GMSH executable is available on the search path (PATH).

**Comment by franciscofnunes** [comment]
Hello... did you find a solution for this issue? I'm having the same problem and I'm not being able to fix it by adding to the PATH

**Comment by MaximilianFranz** [comment]
Probably a more stable variant to find the path of the gmsh executable during runtime is something like: 

```bash 
>>> import subprocess
>>> import os
>>> cmd = "which"
>>> subprocess.call([cmd, "gmsh"])
/opt/conda/envs/modugen-core/bin/gmsh
0
>>>
```

See more here: 
https://stackoverflow.com/questions/55394905/how-to-find-the-location-of-an-executable-in-python

It's important to distinguish between Windows and Linux systems.

**Comment by jonaslindemann** [comment]
I have updated the detection mechanism to be able to find gmsh in more places. Site-packages are also searched now.

Jonas

**Comment by jonaslindemann** [comment]
> Hello... did you find a solution for this issue? I'm having the same problem and I'm not being able to fix it by adding to the PATH

Please check the new release.
