### ISSUE TITLE
What is the license of calfem-matlab?

### ISSUE THREAD

**Issue by sewkokot** [CALFEM/calfem-python#9]
Dear developers of calfem-matlab and calfem-python,

I adapted some functions (among others eldisp2.m beam2crd.m beam2s.m) from matlab to python/matplotlib for the visualiation of OpenSees finite element framework. Can we use those translated functions in OpenSeesPy github repository?
https://github.com/OpenSeesPy-pip/openseespy-pip
https://github.com/zhuminjie/OpenSeesPyDoc

I know that calfem-python has the MIT license, however for example beam2crd.m (from calfem-matlab) has not been ported in the official calfem-python, yet. Actually I also ported beam2crd.m in my fork of calfem-python.

Should I ask for agreement to the authors of particular functions to be able to modify and use interesting parts of calfem-matlab which are not present in calfem-python?

Thank you!

**Comment by jonaslindemann** [comment]
Sorry, for very slow response.... here. I see no problem porting calfem-matlab routines for calfem-python. You could do a pull request for me to check out and merge.

Jonas
